//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domino.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        public static string AbandonarPartida_Button {
            get {
                return ResourceManager.GetString("AbandonarPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string CambiarContraseña_Button {
            get {
                return ResourceManager.GetString("CambiarContraseña_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor llene todos los campos.
        /// </summary>
        public static string CamposVacios {
            get {
                return ResourceManager.GetString("CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar_Button {
            get {
                return ResourceManager.GetString("Cancelar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ContraseñaActual {
            get {
                return ResourceManager.GetString("ContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña cambiada con éxito.
        /// </summary>
        public static string ContraseñaCambiada {
            get {
                return ResourceManager.GetString("ContraseñaCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confrimación de contraseña.
        /// </summary>
        public static string ContraseñaConfirm {
            get {
                return ResourceManager.GetString("ContraseñaConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual esta mal.
        /// </summary>
        public static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string ContraseñasNoCoinciden {
            get {
                return ResourceManager.GetString("ContraseñasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te ha enviado un correo con tu contraseña.
        /// </summary>
        public static string CorreoEnviado {
            get {
                return ResourceManager.GetString("CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay un usuario registrado con ese correo.
        /// </summary>
        public static string CorreoExistente {
            get {
                return ResourceManager.GetString("CorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un correo valido.
        /// </summary>
        public static string CorreoInvalido {
            get {
                return ResourceManager.GetString("CorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CrearPartida_Button {
            get {
                return ResourceManager.GetString("CrearPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado una cuenta asociada a ese correo.
        /// </summary>
        public static string CuentaNoEncontrada {
            get {
                return ResourceManager.GetString("CuentaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas a punto de deshacer la partida, ¿Deseas continuar?.
        /// </summary>
        public static string DeshacerJuego {
            get {
                return ResourceManager.GetString("DeshacerJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dueño de la partida te ha expulsado.
        /// </summary>
        public static string Expulsado {
            get {
                return ResourceManager.GetString("Expulsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        public static string IniciarPartida_Button {
            get {
                return ResourceManager.GetString("IniciarPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IniciarSesion_Button {
            get {
                return ResourceManager.GetString("IniciarSesion_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar multijugador.
        /// </summary>
        public static string JugarMultijugador_Button {
            get {
                return ResourceManager.GetString("JugarMultijugador_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar solo.
        /// </summary>
        public static string JugarSolo_Button {
            get {
                return ResourceManager.GetString("JugarSolo_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string NuevaContraseña {
            get {
                return ResourceManager.GetString("NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dueño ha deshecho la partida.
        /// </summary>
        public static string PartidaDeshecha {
            get {
                return ResourceManager.GetString("PartidaDeshecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string Posicion {
            get {
                return ResourceManager.GetString("Posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar.
        /// </summary>
        public static string Recuperar_Button {
            get {
                return ResourceManager.GetString("Recuperar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Registrarse_Button {
            get {
                return ResourceManager.GetString("Registrarse_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido registrado .
        /// </summary>
        public static string RegistroExitoso {
            get {
                return ResourceManager.GetString("RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Regresar_Button {
            get {
                return ResourceManager.GetString("Regresar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus credenciales de inicio de sesión no coinciden con una cuenta en nuestro sistema.
        /// </summary>
        public static string SinCoincidencia {
            get {
                return ResourceManager.GetString("SinCoincidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña? Has clic aquí.
        /// </summary>
        public static string TextoRecuperar {
            get {
                return ResourceManager.GetString("TextoRecuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo con el que te registraste al cual te mandaremos tu contraseña.
        /// </summary>
        public static string TextoRecupuerarContraseña {
            get {
                return ResourceManager.GetString("TextoRecupuerarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu.
        /// </summary>
        public static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string UnirseAPartida_Button {
            get {
                return ResourceManager.GetString("UnirseAPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver marcadores.
        /// </summary>
        public static string VerMarcadores_Button {
            get {
                return ResourceManager.GetString("VerMarcadores_Button", resourceCulture);
            }
        }
    }
}
