//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domino.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave game.
        /// </summary>
        public static string AbandonarPartida_Button {
            get {
                return ResourceManager.GetString("AbandonarPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string CambiarContraseña_Button {
            get {
                return ResourceManager.GetString("CambiarContraseña_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancelar_Button {
            get {
                return ResourceManager.GetString("Cancelar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string ContraseñaActual {
            get {
                return ResourceManager.GetString("ContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully.
        /// </summary>
        public static string ContraseñaCambiada {
            get {
                return ResourceManager.GetString("ContraseñaCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password confirmation.
        /// </summary>
        public static string ContraseñaConfirm {
            get {
                return ResourceManager.GetString("ContraseñaConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password is wrong.
        /// </summary>
        public static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords do not match.
        /// </summary>
        public static string ContraseñasNoCoinciden {
            get {
                return ResourceManager.GetString("ContraseñasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email with your password has been sent to you.
        /// </summary>
        public static string CorreoEnviado {
            get {
                return ResourceManager.GetString("CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a registered user with that email.
        /// </summary>
        public static string CorreoExistente {
            get {
                return ResourceManager.GetString("CorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string CrearPartida_Button {
            get {
                return ResourceManager.GetString("CrearPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An account associated with that email was not found.
        /// </summary>
        public static string CuentaNoEncontrada {
            get {
                return ResourceManager.GetString("CuentaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to undo the game, do you want to continue?.
        /// </summary>
        public static string DeshacerJuego {
            get {
                return ResourceManager.GetString("DeshacerJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill in all the gaps.
        /// </summary>
        public static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Another time.
        /// </summary>
        public static string EnOtroMomento_Button {
            get {
                return ResourceManager.GetString("EnOtroMomento_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner of the game kicked you out.
        /// </summary>
        public static string Expulsado {
            get {
                return ResourceManager.GetString("Expulsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string IniciarPartida_Button {
            get {
                return ResourceManager.GetString("IniciarPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce a valid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play multiplayer.
        /// </summary>
        public static string JugarMultijugador_Button {
            get {
                return ResourceManager.GetString("JugarMultijugador_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo play.
        /// </summary>
        public static string JugarSolo_Button {
            get {
                return ResourceManager.GetString("JugarSolo_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string LogIn_Button {
            get {
                return ResourceManager.GetString("LogIn_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your login credentials do not match an account in our system.
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NuevaContraseña {
            get {
                return ResourceManager.GetString("NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner has undone the game.
        /// </summary>
        public static string PartidaDeshecha {
            get {
                return ResourceManager.GetString("PartidaDeshecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string Posicion {
            get {
                return ResourceManager.GetString("Posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover.
        /// </summary>
        public static string Recuperar_Button {
            get {
                return ResourceManager.GetString("Recuperar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been registered.
        /// </summary>
        public static string RegistroExitoso {
            get {
                return ResourceManager.GetString("RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Regresar_Button {
            get {
                return ResourceManager.GetString("Regresar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing up.
        /// </summary>
        public static string SignUp_Button {
            get {
                return ResourceManager.GetString("SignUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email with which you registered to which we will send you your password.
        /// </summary>
        public static string TextoRecupuerarContraseña {
            get {
                return ResourceManager.GetString("TextoRecupuerarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the password sent to your email to complete your registration and be able to play.
        /// </summary>
        public static string TextoValidar {
            get {
                return ResourceManager.GetString("TextoValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did you forget your password? Click here.
        /// </summary>
        public static string TextRecover {
            get {
                return ResourceManager.GetString("TextRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string UnirseAPartida_Button {
            get {
                return ResourceManager.GetString("UnirseAPartida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string UnirseAPatida_Button {
            get {
                return ResourceManager.GetString("UnirseAPatida_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate.
        /// </summary>
        public static string Validar_Button {
            get {
                return ResourceManager.GetString("Validar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been verified, log in to play.
        /// </summary>
        public static string VerificacionExitosa {
            get {
                return ResourceManager.GetString("VerificacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View scores.
        /// </summary>
        public static string VerMarcadores_Button {
            get {
                return ResourceManager.GetString("VerMarcadores_Button", resourceCulture);
            }
        }
    }
}
