//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoModelo
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Jugador
    {
        public Nullable<int> Puntaje { get; set; }
        public int JugadorID { get; set; }
        public int UsuarioID { get; set; }
        public int RondaID { get; set; }
    
        public virtual Ronda Ronda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
