//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoModelo
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Ronda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ronda()
        {
            this.Jugador = new ObservableCollection<Jugador>();
        }
    
        public string Ganador { get; set; }
        public int RondaID { get; set; }
        public int JuegoID { get; set; }
    
        public virtual Juego Juego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Jugador> Jugador { get; set; }
    }
}
